# Generated by Django 4.2.9 on 2024-05-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_category_owner_category_image_category_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_item',
            old_name='coupen',
            new_name='coupon',
        ),
    ]
