# Generated by Django 4.2.4 on 2023-08-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product', verbose_name='Variant_name'),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='updated_on',
            field=models.DateField(editable=False),
        ),
    ]
