# Generated by Django 4.2.4 on 2023-08-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_item',
            name='offer',
        ),
        migrations.AddField(
            model_name='product_item',
            name='coupen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product', verbose_name='Product_name'),
        ),
    ]
