# Generated by Django 4.2.4 on 2023-08-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_item_offer_product_item_coupen_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Product_Image',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.category'),
        ),
    ]
