# Generated by Django 4.2.5 on 2023-09-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_item_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='product_image',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='created_by',
            new_name='owner',
        ),
    ]
