# Generated by Django 4.2.8 on 2024-01-28 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_rename_created_by_category_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True)),
                ('display_space', models.CharField(choices=[('Home', 'Home'), ('Category', 'Category'), ('Profile', 'Profile')], default='Profile', max_length=20)),
                ('banner_image', models.ImageField(upload_to=product.models.banner_image_file_path)),
                ('url', models.URLField()),
                ('validity', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'is_seller': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
