# Generated by Django 4.2.13 on 2024-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
