# Generated by Django 4.2.4 on 2023-08-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
