# Generated by Django 4.2.13 on 2024-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('Trending', 'Trending'), ('New Arrival', 'New Arrival'), ('Best Seller', 'Best Seller'), ('Limited Edition', 'Limited Edition'), ('Top Rating', 'Top Rating')], max_length=20, null=True),
        ),
    ]
