# Generated by Django 5.0.7 on 2024-07-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_brand_owner_alter_color_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='owner',
        ),
    ]
