# Generated by Django 4.2.4 on 2023-08-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldsrelatedforeignkey-djangodbmodelsfieldsrelatedforeignkey-djangodbmodelsfieldsrelatedforeignkey'),
        ),
    ]
