# Generated by Django 5.0.7 on 2024-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_image_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
