# Generated by Django 5.0.7 on 2024-11-21 18:44

import django.core.validators
import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_warranty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_review',
            old_name='comment',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='product_review',
            old_name='user',
            new_name='reviewer',
        ),
        migrations.AddField(
            model_name='product_review',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.review_image_file_path)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.product_review')),
            ],
        ),
    ]
