# Generated by Django 4.2.4 on 2023-08-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_item',
            name='slug',
        ),
    ]
