# Generated by Django 4.2.4 on 2023-08-09 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_remove_product_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_item',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Seller_of_product', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
