# Generated by Django 4.2.4 on 2023-09-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_billingaddress'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.billingaddress'),
            preserve_default=False,
        ),
    ]
