# Generated by Django 4.2.5 on 2023-09-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
