# Generated by Django 5.0.7 on 2024-11-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='town',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='address',
            name='company_name',
        ),
        migrations.AddField(
            model_name='address',
            name='tag',
            field=models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Office')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
