# Generated by Django 5.0.7 on 2024-11-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_town_address_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='secondary_mob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
