# Generated by Django 4.2.4 on 2023-09-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='last_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
