# Generated by Django 4.2.3 on 2023-07-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='mobile_no',
        ),
    ]
