# Generated by Django 4.2.3 on 2023-07-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_mobile_user_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
