# Generated by Django 5.0.7 on 2024-07-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
